/**
 * Strong default blueprint bodies for Sub-Agents “Generate templates”.
 * Keep placeholders minimal: {{PROJECT_NAME}}, {{PROJECT_SLUG}}, plus API/data stubs.
 */

import { withComputedDocState } from "./blueprintDocMeta";
import { slugifyProjectName } from "./projectSlug";
import type { BlueprintFileKey, ProjectBlueprint } from "./types";
import { BLUEPRINT_FILE_KEYS } from "./types";

export interface BlueprintTemplateContext {
  projectName: string;
  projectSlug: string;
  entityName: string;
  tableName: string;
  method: string;
  apiPath: string;
}

function slugToPascal(slug: string): string {
  const parts = slug.split(/[-_\s]+/).filter(Boolean);
  if (parts.length === 0) return "Project";
  return parts.map((p) => p[0]!.toUpperCase() + p.slice(1).toLowerCase()).join("");
}

export function buildTemplateContext(projectName: string, projectSlug: string): BlueprintTemplateContext {
  const name = projectName.trim() || "Untitled project";
  const slug = projectSlug.trim() || slugifyProjectName(name) || "project";
  const pascal = slugToPascal(slug);
  const snake = slug.replace(/-/g, "_");
  return {
    projectName: name,
    projectSlug: slug,
    entityName: `${pascal}Record`,
    tableName: `${snake}_records`,
    method: "GET",
    apiPath: `/api/v1/${slug}`,
  };
}

function subst(tmpl: string, c: BlueprintTemplateContext): string {
  return tmpl
    .replaceAll("{{PROJECT_NAME}}", c.projectName)
    .replaceAll("{{PROJECT_SLUG}}", c.projectSlug)
    .replaceAll("{{ENTITY_NAME}}", c.entityName)
    .replaceAll("{{TABLE_NAME}}", c.tableName)
    .replaceAll("{{METHOD}}", c.method)
    .replaceAll("{{PATH}}", c.apiPath);
}

export function generateProjectSpecMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# PROJECT_SPEC.md",
      "",
      "## Project Name",
      "{{PROJECT_NAME}}",
      "",
      "## Project Slug",
      "{{PROJECT_SLUG}}",
      "",
      "## Summary",
      "A short description of the project in 2 to 4 sentences.",
      "",
      "## Business Goal",
      "What business or user problem does this project solve?",
      "",
      "## Primary Users",
      "Who will use this system?",
      "- User type 1",
      "- User type 2",
      "",
      "## Success Criteria",
      "How will we know this project is successful?",
      "- [ ] Criterion 1",
      "- [ ] Criterion 2",
      "- [ ] Criterion 3",
      "",
      "## In Scope",
      "- Feature 1",
      "- Feature 2",
      "- Feature 3",
      "",
      "## Out of Scope",
      "- Exclusion 1",
      "- Exclusion 2",
      "",
      "## Tech Stack",
      "- Frontend:",
      "- Backend:",
      "- Database:",
      "- Hosting/Runtime:",
      "- Auth:",
      "- Storage:",
      "- Testing:",
      "",
      "## Architecture Summary",
      "- Main user-facing application",
      "- API/service layer",
      "- Database/storage layer",
      "- Background jobs/workflows",
      "- AI coordinator/sub-agent orchestration",
      "",
      "## Constraints",
      "- Must run on Cloudflare Workers",
      "- Must use D1",
      "- Must not use long-running background servers",
      "- Must support mobile browsers",
      "",
      "## Non-Functional Requirements",
      "- Performance:",
      "- Reliability:",
      "- Security:",
      "- Accessibility:",
      "- Observability:",
      "",
      "## Acceptance Criteria",
      "- [ ] Users can …",
      "- [ ] System stores …",
      "- [ ] Admin can …",
      "- [ ] Tests cover …",
      "",
      "## Open Questions",
      "- Question 1",
      "- Question 2",
    ].join("\n"),
    c
  );
}

export function generateRoadmapMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# ROADMAP.md",
      "",
      "## Project",
      "{{PROJECT_NAME}}",
      "",
      "## Status Legend",
      "- `todo` · `in_progress` · `blocked` · `review` · `done`",
      "",
      "## Milestone 1: Foundation",
      "- [ ] Define project structure",
      "- [ ] Establish shared types",
      "- [ ] Set up core routes/endpoints",
      "- [ ] Set up data models",
      "- [ ] Add initial tests",
      "",
      "## Milestone 2: Core Features",
      "- [ ] Implement feature A",
      "- [ ] Implement feature B",
      "",
      "## Milestone 3: Integration",
      "- [ ] Connect frontend to backend",
      "- [ ] Add persistence",
      "- [ ] Add error handling",
      "",
      "## Milestone 4: Review and Hardening",
      "- [ ] Improve tests",
      "- [ ] Add observability/logging",
      "- [ ] Prepare deployment",
      "",
      "## Atomic Task Backlog",
      "",
      "### TASK-001",
      "- Title: Define shared domain types",
      "- Status: todo",
      "- Owner: coordinator",
      "- Depends on: none",
      "- Files/Scope: `/src/shared/types.ts`",
      "- Acceptance Criteria: Shared domain types are defined; no duplicate conflicting shapes.",
      "",
      "### TASK-002",
      "- Title: Implement initial data schema",
      "- Status: todo",
      "- Owner: coder",
      "- Depends on: TASK-001",
      "- Acceptance Criteria: Schema matches DATA_MODELS.md",
      "",
      "### TASK-003",
      "- Title: Verify schema and type alignment",
      "- Status: todo",
      "- Owner: tester",
      "- Depends on: TASK-002",
      "- Acceptance Criteria: Tester confirms schema/types alignment",
      "",
      "## Blockers",
      "- None yet",
      "",
      "## Notes",
      "Coordinator should prefer TASK-* sections for delegation.",
    ].join("\n"),
    c
  );
}

export function generateDataModelsMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# DATA_MODELS.md",
      "",
      "## Overview",
      "Source-of-truth data structures for {{PROJECT_NAME}}.",
      "",
      "## Data Storage Strategy",
      "- Primary database:",
      "- Secondary storage:",
      "- Cache/session storage:",
      "- Files/artifacts storage:",
      "",
      "## Domain Entities",
      "- Entity A",
      "- Entity B",
      "",
      "---",
      "",
      "## Entity: {{ENTITY_NAME}}",
      "",
      "### Purpose",
      "What this entity represents.",
      "",
      "### Fields",
      "| Field | Type | Required | Description |",
      "|------|------|----------|-------------|",
      "| id | string | yes | Unique identifier |",
      "| createdAt | string | yes | ISO timestamp |",
      "| updatedAt | string | yes | ISO timestamp |",
      "",
      "### Relationships",
      "- Belongs to:",
      "- Has many:",
      "",
      "### Example JSON",
      "```json",
      "{",
      '  "id": "example-id",',
      '  "createdAt": "2026-01-01T00:00:00.000Z",',
      '  "updatedAt": "2026-01-01T00:00:00.000Z"',
      "}",
      "```",
      "",
      "## Database Tables (SQL/D1)",
      "",
      "### Table: {{TABLE_NAME}}",
      "| Column | Type | Nullable | Notes |",
      "|--------|------|----------|-------|",
      "| id | TEXT | no | Primary key |",
      "",
      "## Shared Types Contract",
      "- Project",
      "- Task",
      "- User",
      "- ApiResponse (generic success/error wrapper)",
      "",
      "## Invariants",
      "- A task must belong to a valid project",
      "- Status must be one of the allowed enum values",
      "",
      "## Open Questions",
      "- Question 1",
    ].join("\n"),
    c
  );
}

export function generateApiDesignMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# API_DESIGN.md",
      "",
      "## Overview",
      "API contract for {{PROJECT_NAME}}.",
      "",
      "## API Style",
      "- REST / RPC / hybrid:",
      "- Base path:",
      "- Auth approach:",
      "- Response format:",
      "- Error format:",
      "",
      "## Conventions",
      "- Timestamps are ISO strings",
      "- IDs are strings",
      "- Structured JSON errors",
      "",
      "---",
      "",
      "## Endpoint: {{METHOD}} {{PATH}}",
      "",
      "### Purpose",
      "Example read operation.",
      "",
      "### Auth",
      "- Required / Optional / None",
      "",
      "### Request",
      "#### Path Params",
      "| Name | Type | Required | Description |",
      "|------|------|----------|-------------|",
      "",
      "#### Body",
      "```json",
      "{",
      '  "example": true',
      "}",
      "```",
      "",
      "### Response",
      "```json",
      "{",
      '  "ok": true,',
      '  "data": {}',
      "}",
      "```",
      "",
      "## Planned Endpoints",
      "- GET /...",
      "- POST /...",
      "",
      "## Contract Rules",
      "- Do not invent fields not listed here",
      "- Keep shared types aligned with DATA_MODELS.md",
      "",
      "## Open Questions",
      "- Question 1",
    ].join("\n"),
    c
  );
}

export function generateAiInstructionsMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# AI_INSTRUCTIONS.md",
      "",
      "## Purpose",
      "Mandatory instructions for CoordinatorAgent, CoderAgent, and TesterAgent working on **{{PROJECT_NAME}}** (`{{PROJECT_SLUG}}`).",
      "",
      "## Global Rules",
      "- Follow PROJECT_SPEC.md, ROADMAP.md, FILE_STRUCTURE.md (when present), DATA_MODELS.md, and API_DESIGN.md as source of truth.",
      "- Do not invent architecture not documented in blueprint files.",
      "- Do not modify unrelated files.",
      "- Scope changes to the assigned task.",
      "- Prefer small, reviewable diffs.",
      "- If blocked, document the blocker instead of risky assumptions.",
      "",
      "## CoordinatorAgent",
      "- Decompose roadmap into atomic tasks.",
      "- Build focused context packages per task.",
      "- Route implementation to CoderAgent and verification to TesterAgent.",
      "- Track task/run state; avoid broad edits unless required.",
      "",
      "## CoderAgent",
      "- Implement only the assigned task.",
      "- Obey DATA_MODELS.md and API_DESIGN.md.",
      "- Reuse existing types/components.",
      "- Do not invent schemas/endpoints without blueprint evidence.",
      "- For control-plane shared workspace work, target **implementation** patches at **staging/<logical-path>** per **FILE_STRUCTURE.md** by default; do **not** use canonical repo roots (`src/`, `frontend/`, `db/`, …) in unified diffs unless **FILE_STRUCTURE.md** or the task explicitly allows it (see coordinator marker for direct canonical paths). Materialization maps staging into real paths — do not invent repo layout.",
      "",
      "## TesterAgent",
      "- Verify against blueprint files with evidence.",
      "- No unauthorized writes.",
      "- Pass/fail with concrete reasons.",
      "- Treat pending **implementation** patches as invalid when they violate **FILE_STRUCTURE.md** placement rules, or mix **staging/** paths with canonical roots, unless **FILE_STRUCTURE.md** or the task explicitly allows canonical paths (see coordinator marker) — **VERDICT: FAIL** and list offending paths.",
      "",
      "## Forbidden Actions",
      "- Do not edit secrets/bindings casually.",
      "- Do not silently widen scope.",
      "",
      "## Definition of Done",
      "- Matches blueprint contracts",
      "- Validation passes",
      "- Status updated appropriately",
      "",
      "## Escalation",
      "- Blueprint conflicts, missing files, ambiguous scope, or risky migrations.",
    ].join("\n"),
    c
  );
}

export function generateContextMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# CONTEXT.md",
      "",
      "## Current Project State",
      "Summarize what exists today for **{{PROJECT_NAME}}**.",
      "",
      "## What Has Already Been Built",
      "- Item 1",
      "- Item 2",
      "",
      "## Current Architecture Notes",
      "- Main runtime:",
      "- Storage:",
      "- Auth:",
      "- API structure:",
      "- Frontend structure:",
      "- Coordinator/sub-agent structure:",
      "",
      "## Current Environment",
      "- Environment name:",
      "- Key bindings/features:",
      "- Known disabled features:",
      "",
      "## Recent Changes",
      "- Change 1",
      "",
      "## Known Issues",
      "- Issue 1",
      "",
      "## Pending Decisions",
      "- Decision 1",
      "",
      "## Useful File Paths",
      "- `/src/...`",
      "- `/frontend/...`",
      "- `/db/...`",
      "- `/projects/{{PROJECT_SLUG}}/...`",
      "",
      "## Testing Notes",
      "- How to test locally:",
      "- Smoke tests:",
      "",
      "## Notes for Agents",
      "- Start with PROJECT_SPEC + ROADMAP before coding.",
      "- Reuse existing patterns; respect shared contracts.",
      "- Honor **FILE_STRUCTURE.md** for staged paths and materialization intent.",
    ].join("\n"),
    c
  );
}

export function generateFileStructureMd(c: BlueprintTemplateContext): string {
  return subst(
    [
      "# FILE_STRUCTURE.md",
      "",
      "## Overview",
      "This document defines the canonical file layout for **{{PROJECT_NAME}}** and the staging conventions agents must follow while producing patches.",
      "",
      "The materialization step maps staged files into final repo paths. Agents should not guess final repo structure beyond what is documented here and in the other blueprint files.",
      "",
      "---",
      "",
      "## Canonical Repo Layout",
      "",
      "### Backend",
      "- `src/api/` — API route handlers and request/response logic",
      "- `src/services/` — business logic and orchestration helpers",
      "- `src/shared/` — shared TypeScript types and utilities",
      "- `src/db/` — database access helpers, query helpers, and D1 integration",
      "",
      "### Database",
      "- `db/schema.sql` — canonical D1 / SQLite schema",
      "- `db/migrations/` — future schema migrations",
      "",
      "### Frontend",
      "- `frontend/src/components/` — reusable UI components",
      "- `frontend/src/pages/` — page-level views",
      "- `frontend/src/lib/` — frontend API clients and helpers",
      "- `frontend/src/types/` — frontend-only TypeScript types",
      "",
      "### Tests",
      "- `tests/` — backend and integration tests",
      "- `frontend/src/__tests__/` — frontend tests where applicable",
      "",
      "---",
      "",
      "## Staging Convention",
      "",
      "During coordinator/coder/tester orchestration, implementation patches should use staged paths by default.",
      "",
      "Use:",
      "- `staging/db/schema.sql`",
      "- `staging/api/<feature>.ts`",
      "- `staging/services/<feature>.ts`",
      "- `staging/shared/<name>.ts`",
      "- `staging/components/<ComponentName>.tsx`",
      "- `staging/pages/<PageName>.tsx`",
      "- `staging/tests/<feature>.test.ts`",
      "",
      "Do not write directly to final repo paths such as:",
      "- `src/...`",
      "- `frontend/src/...`",
      "- `db/...`",
      "",
      "unless this document explicitly allows an exception for a named path **or** the coordinator task states that canonical targets are required.",
      "",
      "---",
      "",
      "## Materialization Mapping",
      "",
      "The materializer maps staged files into repo paths (preset-dependent). Default mapping **intent**:",
      "",
      "| Staged path | Final repo path |",
      "|-------------|-----------------|",
      "| `staging/db/schema.sql` | `db/schema.sql` |",
      "| `staging/api/<name>.ts` | `src/api/<name>.ts` |",
      "| `staging/services/<name>.ts` | `src/services/<name>.ts` |",
      "| `staging/shared/<name>.ts` | `src/shared/<name>.ts` |",
      "| `staging/components/<name>.tsx` | `frontend/src/components/<name>.tsx` |",
      "| `staging/pages/<name>.tsx` | `frontend/src/pages/<name>.tsx` |",
      "| `staging/tests/<name>.test.ts` | `tests/<name>.test.ts` |",
      "",
      "---",
      "",
      "## Backend Files",
      "",
      "- Handlers live under `staging/api/` → materialize to `src/api/`.",
      "- Services under `staging/services/` → `src/services/`.",
      "",
      "## Frontend Files",
      "",
      "- Components under `staging/components/` → `frontend/src/components/`.",
      "- Pages under `staging/pages/` → `frontend/src/pages/`.",
      "",
      "## Database Files",
      "",
      "- Schema under `staging/db/` → `db/`.",
      "",
      "## Shared Types",
      "",
      "- Cross-cutting TS types under `staging/shared/` → `src/shared/`.",
      "",
      "## Testing Files",
      "",
      "- Backend/integration tests under `staging/tests/` → `tests/`.",
      "",
      "---",
      "",
      "## Rules for Agents",
      "",
      "1. CoderAgent places implementation patches under `staging/` by default.",
      "2. Choose staged paths that map cleanly to rows in the Materialization Mapping table.",
      "3. TesterAgent fails verification when paths conflict with this document unless an explicit exception is documented here or in the task.",
      "4. Do not invent new top-level directories without updating this file and PROJECT_SPEC.",
      "5. Materialization performs path rewriting; agents must not rely on ad-hoc guesses.",
      "6. Keep placement aligned with PROJECT_SPEC.md, API_DESIGN.md, and DATA_MODELS.md.",
      "",
      "---",
      "",
      "## Examples",
      "",
      "### Shared types",
      "- Staged: `staging/shared/types.ts` → Final: `src/shared/types.ts`",
      "",
      "### Database schema",
      "- Staged: `staging/db/schema.sql` → Final: `db/schema.sql`",
      "",
      "### API endpoints",
      "- Staged: `staging/api/projects.ts` → Final: `src/api/projects.ts`",
      "",
      "### Component",
      "- Staged: `staging/components/ProjectList.tsx` → Final: `frontend/src/components/ProjectList.tsx`",
      "",
      "---",
      "",
      "## Review Rules",
      "",
      "A verification task should **FAIL** when:",
      "- files are placed inconsistently with this document,",
      "- staged and canonical repo paths are mixed without documented permission,",
      "- generated files do not map cleanly to the canonical layout,",
      "- the implementation requires a new directory not documented here.",
    ].join("\n"),
    c
  );
}

const GENERATORS: Record<BlueprintFileKey, (c: BlueprintTemplateContext) => string> = {
  "PROJECT_SPEC.md": generateProjectSpecMd,
  "ROADMAP.md": generateRoadmapMd,
  "DATA_MODELS.md": generateDataModelsMd,
  "API_DESIGN.md": generateApiDesignMd,
  "AI_INSTRUCTIONS.md": generateAiInstructionsMd,
  "CONTEXT.md": generateContextMd,
  "FILE_STRUCTURE.md": generateFileStructureMd,
};

/** Returns a blueprint slice; use `only` to regenerate a single file for merge clients. */
export function buildGeneratedTemplateBlueprint(
  projectName: string,
  projectSlug: string,
  only?: BlueprintFileKey
): ProjectBlueprint {
  const ctx = buildTemplateContext(projectName, projectSlug);
  const keys: BlueprintFileKey[] = only ? [only] : [...BLUEPRINT_FILE_KEYS];
  const docs: ProjectBlueprint["docs"] = {};
  const templateFingerprints: ProjectBlueprint["templateFingerprints"] = {};
  for (const k of keys) {
    const body = GENERATORS[k](ctx);
    docs[k] = body;
    templateFingerprints[k] = body;
  }
  return withComputedDocState({ schemaVersion: 2, docs, templateFingerprints });
}
