import {
  uploadWorkersPromotionPreviewVersion,
} from "./cloudflareWorkersVersionUpload";
import type { PreviewDeployAdapter, PreviewDeployRequest, PreviewDeployResult } from "./previewDeployTypes";

export interface WorkersVersionUploadPreviewDeployAdapterOptions {
  accountId: string;
  apiToken: string;
  uploadScriptName: string;
  compatibilityDate: string;
  fetchFn?: typeof fetch;
}

function mergeAudit(
  inner: PreviewDeployResult["audit"],
  backendSuffix: string,
  extras: Partial<PreviewDeployResult["audit"]>
): PreviewDeployResult["audit"] {
  return {
    ...inner,
    adapterBackend: `${inner.adapterBackend ?? "promotion_verified"}${backendSuffix}`,
    ...extras,
  };
}

/**
 * Wraps a promotion-verified preview adapter. After inner **success**, uploads a new **Workers Version**
 * via Cloudflare API to {@link WorkersVersionUploadPreviewDeployAdapterOptions.uploadScriptName}.
 *
 * Uses a tiny stub Worker (no Durable Objects) so **version preview URLs** can be generated by Cloudflare.
 * This is intentionally **not** the main `edgeclaw-truth-agent` Worker binary — deploy that via Wrangler/CI.
 */
export function createWorkersVersionUploadPreviewDeployAdapter(
  inner: PreviewDeployAdapter,
  options: WorkersVersionUploadPreviewDeployAdapterOptions
): PreviewDeployAdapter {
  const {
    accountId,
    apiToken,
    uploadScriptName,
    compatibilityDate,
    fetchFn = globalThis.fetch.bind(globalThis),
  } = options;

  return {
    async deploy(request: PreviewDeployRequest): Promise<PreviewDeployResult> {
      const innerResult = await inner.deploy(request);
      if (innerResult.status !== "succeeded") {
        return innerResult;
      }

      const up = await uploadWorkersPromotionPreviewVersion({
        accountId,
        apiToken,
        uploadScriptName,
        manifestDigest: request.bundleRef.manifestDigest?.trim() ?? "",
        bundleId: request.manifest.bundleId,
        compatibilityDate,
        fetchFn,
      });

      if (!up.ok) {
        return {
          status: "failed",
          failureCategory: "adapter_error",
          audit: mergeAudit(innerResult.audit, "+cf_workers_version_upload_failed", {}),
          error: up.error,
          previewUrl: innerResult.previewUrl,
          previewIdentifier: innerResult.previewIdentifier,
        };
      }

      const { versionId, previewUrl: uploadPreviewUrl, hasPreview } = up.data;
      const mergedPreviewUrl = uploadPreviewUrl ?? innerResult.previewUrl;

      return {
        status: "succeeded",
        previewUrl: mergedPreviewUrl,
        previewIdentifier: versionId,
        audit: mergeAudit(innerResult.audit, "+cf_workers_version_upload", {
          workersApiVersionId: versionId,
          workersVersionHasPreview: hasPreview,
        }),
      };
    },
  };
}
